version: "3.7"

services:
  app:
    platform: linux/amd64
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
      - bundle_data:/bundle
    command: sh /scripts/command.sh
    # command: bundle exec rails s -p 3000 -b 0.0.0.0
    stdin_open: true
    tty: true

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: on-failure
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: <%= ENV['DATABASE_ROOT_PASSWORD'] %>
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3310:3306
  front:
    build:
      dockerfile: docker/front/Dockerfile
    command: |
      yarn run dev
    volumes:
      - ./front:/app:cached
    ports:
      #Host computer port: Port in Docker
      - 8080:3000
    depends_on:
      - app
volumes:
  mysql_data:
  bundle_data:
